'use strict'
/* Sensing devices list
  Generated from FIESTA IoT ontology with this Jena SPARQL script:
  1 PREFIX qu:<http://purl.org/NET/ssnx/qu/qu#>
  2 PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
  3 PREFIX ssn:<http://purl.oclc.org/NET/ssnx/ssn#>
  4 SELECT (strafter(str(?subClass), "#") AS ?quantityKind)
  5 WHERE { ?subClass rdfs:subClassOf* ssn:SensingDevice. } 
  $ bin/sparql --data=http://ontology.fiesta-iot.eu/ontologyDocs/fiesta-iot.owl --query=./rq --results=TSV
  Reference paper: R. Agarwal, D. Farnandez, T. Elsaleh, A.Gyrard, J. Lanza, L. Sanchez, N. Georgantas, V. Issarny, "Unified IoT Ontology to Enable Interoperability and Federation of Testbeds", 3rd IEEE WF-IoT, pp. 70-75, Reston USA, 12-14 December 2016
*/

export default [
"Accelerometer",
"AirHumiditySensor",
"AirPollutantSensor",
"AirThermometer",
"AlcoholLevelSensor",
"AtmosphericPressureSensor",
"BloodPressureSensor",
"BoardThermometer",
"BoardVoltageSensor",
"BodyThermometer",
"CholesterolSensor",
"Clock",
"CloudCoverSensor",
"CO2Sensor",
"ConductivitySensor",
"COSensor",
"Counter",
"CurrentSensor",
"DeltaDewPointSensor",
"DeviceUptimeClock",
"DewPointSensor",
"DirectionOfArrivalSensor",
"DistanceNextBusSensor",
"DistanceSensor",
"DoorStateSensor",
"DustSensor",
"ECG",
"ElectricalSensor",
"ElectricFieldSensor",
"EnergyMeter",
"FallDetector",
"FrequencySensor",
"FuelLevel",
"GasDetector",
"GaseousPollutantSensor",
"Glucometer",
"GPSSensor",
"GyrometerSensor",
"GyroscopeSensor",
"H2SSensor",
"HeartBeatSensor",
"HumanPresenceDetector",
"HumiditySensor",
"Hydrophone",
"IEEE802154InterfaceEnergyMeter",
"ImageSensor",
"LeafWetnessSensor",
"LightSensor",
"LoRaInterface",
"LoRaInterfaceEnergyMeter",
"Magnetometer",
"MethaneSensor",
"NH3Sensor",
"NO2Sensor",
"NOSensor",
"O3Sensor",
"Odometer",
"OpticalDustSensor",
"OxidationReductionPotentialSensor",
"OxygenSensor",
"Pedometer",
"PeopleCountSensor",
"PHSensor",
"PrecipitationSensor",
"PresenceDetector",
"PressureSensor",
"ProximitySensor",
"PulseOxymeter",
"RadiationParticleDetector",
"RoadSurfaceThermometer",
"SaltMeter",
"Seismometer",
"SensingDevice",
"ShakeSensor",
"SkinConductanceSensor",
"SmokeDetector",
"SO2Sensor",
"SoilHumiditySensor",
"SoilThermometer",
"SolarRadiationSensor",
"SoundSensor",
"SpeedSensor",
"SunPositionDirectionSensor",
"SunPositionElevationSensor",
"Thermometer",
"ThrottleSensor",
"TimeOfArrivalNextBusSensor",
"TimeOfArrivalSensor",
"TouchSensor",
"UltrasonicSensor",
"VehicleCountSensor",
"VehiclePresenceDetector",
"VisibilitySensor",
"VOCSensor",
"VoiceCommandSensor",
"VoltageSensor",
"WaterConductivitySensor",
"WaterNH4IonSensor",
"WaterNO3IonSensor",
"WaterO2IonSensor",
"WaterPHSensor",
"WaterThermometer",
"WeightSensor",
"WiFiInterfaceEnergyMeter",
"WindChillSensor",
"WindDirectionSensor",
"WindSpeedSensor"

]
