/**
 * WAZIUP API
 * Applications API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/SocialMessage', 'model/SocialMessageBatch'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/SocialMessage'), require('../model/SocialMessageBatch'));
  } else {
    // Browser globals (root is window)
    if (!root.WaziupApi) {
      root.WaziupApi = {};
    }
    root.WaziupApi.SocialsApi = factory(root.WaziupApi.ApiClient, root.WaziupApi.Error, root.WaziupApi.SocialMessage, root.WaziupApi.SocialMessageBatch);
  }
}(this, function(ApiClient, Error, SocialMessage, SocialMessageBatch) {
  'use strict';

  /**
   * Socials service.
   * @module api/SocialsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SocialsApi. 
   * @alias module:api/SocialsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the domainsDomainSocialsBatchPost operation.
     * @callback module:api/SocialsApi~domainsDomainSocialsBatchPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * post several message to social networks
     * @param {String} domain 
     * @param {module:model/SocialMessageBatch} data social message
     * @param {module:api/SocialsApi~domainsDomainSocialsBatchPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainSocialsBatchPost = function(domain, data, callback) {
      var postBody = data;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainSocialsBatchPost");
      }

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling domainsDomainSocialsBatchPost");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/socials/batch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainSocialsGet operation.
     * @callback module:api/SocialsApi~domainsDomainSocialsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SocialMessage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all messages sent
     * @param {String} domain 
     * @param {module:api/SocialsApi~domainsDomainSocialsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SocialMessage}
     */
    this.domainsDomainSocialsGet = function(domain, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainSocialsGet");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SocialMessage;

      return this.apiClient.callApi(
        '/domains/{domain}/socials', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainSocialsMsgIdDelete operation.
     * @callback module:api/SocialsApi~domainsDomainSocialsMsgIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete a message to social networks
     * @param {String} domain 
     * @param {String} msgId 
     * @param {module:api/SocialsApi~domainsDomainSocialsMsgIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainSocialsMsgIdDelete = function(domain, msgId, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainSocialsMsgIdDelete");
      }

      // verify the required parameter 'msgId' is set
      if (msgId === undefined || msgId === null) {
        throw new Error("Missing the required parameter 'msgId' when calling domainsDomainSocialsMsgIdDelete");
      }


      var pathParams = {
        'domain': domain,
        'msg_id': msgId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/socials/{msg_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainSocialsMsgIdGet operation.
     * @callback module:api/SocialsApi~domainsDomainSocialsMsgIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SocialMessage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get one message
     * @param {String} domain 
     * @param {String} msgId 
     * @param {module:api/SocialsApi~domainsDomainSocialsMsgIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SocialMessage}
     */
    this.domainsDomainSocialsMsgIdGet = function(domain, msgId, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainSocialsMsgIdGet");
      }

      // verify the required parameter 'msgId' is set
      if (msgId === undefined || msgId === null) {
        throw new Error("Missing the required parameter 'msgId' when calling domainsDomainSocialsMsgIdGet");
      }


      var pathParams = {
        'domain': domain,
        'msg_id': msgId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SocialMessage;

      return this.apiClient.callApi(
        '/domains/{domain}/socials/{msg_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainSocialsPost operation.
     * @callback module:api/SocialsApi~domainsDomainSocialsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * post a message to social networks
     * @param {String} domain 
     * @param {module:model/SocialMessage} data social message
     * @param {module:api/SocialsApi~domainsDomainSocialsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainSocialsPost = function(domain, data, callback) {
      var postBody = data;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainSocialsPost");
      }

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling domainsDomainSocialsPost");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/socials', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
