/**
 * WAZIUP API
 * Applications API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthBody', 'model/User', 'model/UserUpdateBody'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AuthBody'), require('../model/User'), require('../model/UserUpdateBody'));
  } else {
    // Browser globals (root is window)
    if (!root.WaziupApi) {
      root.WaziupApi = {};
    }
    root.WaziupApi.UsersApi = factory(root.WaziupApi.ApiClient, root.WaziupApi.AuthBody, root.WaziupApi.User, root.WaziupApi.UserUpdateBody);
  }
}(this, function(ApiClient, AuthBody, User, UserUpdateBody) {
  'use strict';

  /**
   * Users service.
   * @module api/UsersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new UsersApi. 
   * @alias module:api/UsersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the domainsDomainAuthPost operation.
     * @callback module:api/UsersApi~domainsDomainAuthPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the access token for subsequent calls
     * @param {String} domain 
     * @param {module:model/AuthBody} credentials auth credentials
     * @param {module:api/UsersApi~domainsDomainAuthPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainAuthPost = function(domain, credentials, callback) {
      var postBody = credentials;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainAuthPost");
      }

      // verify the required parameter 'credentials' is set
      if (credentials === undefined || credentials === null) {
        throw new Error("Missing the required parameter 'credentials' when calling domainsDomainAuthPost");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/auth/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainUsersGet operation.
     * @callback module:api/UsersApi~domainsDomainUsersGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all users in a realm
     * @param {String} domain 
     * @param {module:api/UsersApi~domainsDomainUsersGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainUsersGet = function(domain, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainUsersGet");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/users/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainUsersPost operation.
     * @callback module:api/UsersApi~domainsDomainUsersPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new user in a realm
     * @param {String} domain 
     * @param {module:model/User} user user object
     * @param {module:api/UsersApi~domainsDomainUsersPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainUsersPost = function(domain, user, callback) {
      var postBody = user;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainUsersPost");
      }

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling domainsDomainUsersPost");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/users/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainUsersSearchGet operation.
     * @callback module:api/UsersApi~domainsDomainUsersSearchGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search users with specific criteria
     * @param {String} domain 
     * @param {module:api/UsersApi~domainsDomainUsersSearchGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainUsersSearchGet = function(domain, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainUsersSearchGet");
      }


      var pathParams = {
        'domain': domain
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/users/search/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainUsersUseridDelete operation.
     * @callback module:api/UsersApi~domainsDomainUsersUseridDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} domain 
     * @param {String} userid 
     * @param {module:api/UsersApi~domainsDomainUsersUseridDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainUsersUseridDelete = function(domain, userid, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainUsersUseridDelete");
      }

      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling domainsDomainUsersUseridDelete");
      }


      var pathParams = {
        'domain': domain,
        'userid': userid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/users/{userid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainUsersUseridGet operation.
     * @callback module:api/UsersApi~domainsDomainUsersUseridGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} domain 
     * @param {String} userid 
     * @param {module:api/UsersApi~domainsDomainUsersUseridGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainUsersUseridGet = function(domain, userid, callback) {
      var postBody = null;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainUsersUseridGet");
      }

      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling domainsDomainUsersUseridGet");
      }


      var pathParams = {
        'domain': domain,
        'userid': userid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/users/{userid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the domainsDomainUsersUseridPut operation.
     * @callback module:api/UsersApi~domainsDomainUsersUseridPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} domain 
     * @param {String} userid 
     * @param {module:model/UserUpdateBody} data user data to update
     * @param {module:api/UsersApi~domainsDomainUsersUseridPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.domainsDomainUsersUseridPut = function(domain, userid, data, callback) {
      var postBody = data;

      // verify the required parameter 'domain' is set
      if (domain === undefined || domain === null) {
        throw new Error("Missing the required parameter 'domain' when calling domainsDomainUsersUseridPut");
      }

      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling domainsDomainUsersUseridPut");
      }

      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling domainsDomainUsersUseridPut");
      }


      var pathParams = {
        'domain': domain,
        'userid': userid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/domains/{domain}/users/{userid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
