/**
 * WAZIUP API
 * Applications API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaziupApi);
  }
}(this, function(expect, WaziupApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaziupApi.NotificationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotificationsApi', function() {
    describe('domainsDomainNotificationsGet', function() {
      it('should call domainsDomainNotificationsGet successfully', function(done) {
        //uncomment below and update the code to test domainsDomainNotificationsGet
        //instance.domainsDomainNotificationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainNotificationsNotifIdDelete', function() {
      it('should call domainsDomainNotificationsNotifIdDelete successfully', function(done) {
        //uncomment below and update the code to test domainsDomainNotificationsNotifIdDelete
        //instance.domainsDomainNotificationsNotifIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainNotificationsNotifIdGet', function() {
      it('should call domainsDomainNotificationsNotifIdGet successfully', function(done) {
        //uncomment below and update the code to test domainsDomainNotificationsNotifIdGet
        //instance.domainsDomainNotificationsNotifIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainNotificationsPost', function() {
      it('should call domainsDomainNotificationsPost successfully', function(done) {
        //uncomment below and update the code to test domainsDomainNotificationsPost
        //instance.domainsDomainNotificationsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
