/**
 * WAZIUP API
 * Applications API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaziupApi);
  }
}(this, function(expect, WaziupApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaziupApi.SocialsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SocialsApi', function() {
    describe('domainsDomainSocialsBatchPost', function() {
      it('should call domainsDomainSocialsBatchPost successfully', function(done) {
        //uncomment below and update the code to test domainsDomainSocialsBatchPost
        //instance.domainsDomainSocialsBatchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainSocialsGet', function() {
      it('should call domainsDomainSocialsGet successfully', function(done) {
        //uncomment below and update the code to test domainsDomainSocialsGet
        //instance.domainsDomainSocialsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainSocialsMsgIdDelete', function() {
      it('should call domainsDomainSocialsMsgIdDelete successfully', function(done) {
        //uncomment below and update the code to test domainsDomainSocialsMsgIdDelete
        //instance.domainsDomainSocialsMsgIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainSocialsMsgIdGet', function() {
      it('should call domainsDomainSocialsMsgIdGet successfully', function(done) {
        //uncomment below and update the code to test domainsDomainSocialsMsgIdGet
        //instance.domainsDomainSocialsMsgIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsDomainSocialsPost', function() {
      it('should call domainsDomainSocialsPost successfully', function(done) {
        //uncomment below and update the code to test domainsDomainSocialsPost
        //instance.domainsDomainSocialsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
