/**
 * WAZIUP API
 * Applications API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WaziupApi);
  }
}(this, function(expect, WaziupApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WaziupApi.SocialsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SocialsApi', function() {
    describe('createSocialMsgsBatch', function() {
      it('should call createSocialMsgsBatch successfully', function(done) {
        //uncomment below and update the code to test createSocialMsgsBatch
        //instance.createSocialMsgsBatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSocialMsgs', function() {
      it('should call getSocialMsgs successfully', function(done) {
        //uncomment below and update the code to test getSocialMsgs
        //instance.getSocialMsgs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSocialsMsg', function() {
      it('should call deleteSocialsMsg successfully', function(done) {
        //uncomment below and update the code to test deleteSocialsMsg
        //instance.deleteSocialsMsg(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSocialsMsg', function() {
      it('should call getSocialsMsg successfully', function(done) {
        //uncomment below and update the code to test getSocialsMsg
        //instance.getSocialsMsg(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSocialMsg', function() {
      it('should call createSocialMsg successfully', function(done) {
        //uncomment below and update the code to test createSocialMsg
        //instance.createSocialMsg(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
